---
title: "South Gate Purple Air Explorer"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    source: embed
runtime: shiny
---

```{r}
#created by Ajay Pillarisetti and Jason Vargo
```

```{r global, include=FALSE}
Sys.setenv(TZ="America/Los_Angeles")

library(lubridate)
library(data.table)
library(plyr)
library(DT)
library(ggplot2)
library(dygraphs)
library(flexdashboard)
library(leaflet)

#import and lightly clean data
input_data <- readRDS('primary_scsgdata.rds')
setnames(input_data, 'round_dt', 'Timestamp')
input_data[, Timestamp := Timestamp-28800]
input_data[, Date:=as.Date(Timestamp, tz="America/Los_Angeles")]
input_data[, station_id:=as.numeric(station_id)]
long_data <- melt(input_data[, -c('Date')], id.var=c('Timestamp', 'lat', 'long', 'station_id', 'sensor'))
date_filter <- input_data[, unique(Date), by=station_id]
unique_sensors <- input_data[, unique(station_id)]
sensors_sp <- input_data[,.(latitude = max(as.numeric(lat)), longitude = max(as.numeric(long))), by = station_id]
```

Inputs {.sidebar}
=====================================
```{r}
textOutput("sampleTitle")
HTML("<br>")

output$map <- renderLeaflet({
  
  sensors_sp[, size := ifelse(station_id == input$sensor, 5, 3)]
  sensors_sp[, color := ifelse(station_id == input$sensor, "red", "gray50")]
  sensors_sp[, stroke := ifelse(station_id == input$sensor, 1, 0)]
  
  leaflet(data = sensors_sp, height = "100" )  %>%
      addProviderTiles(providers$CartoDB.Positron) %>% # CartoDB.Positron  or  OpenStreetMap.BlackAndWhite
      addCircleMarkers(
        radius = ~ size,
        color = ~ color,
        stroke = ~ stroke,
        fillOpacity = 0.7,
        label = ~ paste0("Station Number: ", station_id),
        popup = ~ paste0("Station Number: ", station_id)
      ) 
})

selectInput('sensor', HTML("<strong>Select a sensor</strong><br>"), choices = unique_sensors, selected = 7, multiple = FALSE, selectize = TRUE, width = NULL, size = NULL)

output$date_selector <- renderUI({
  dateRangeInput('date_select', HTML("<strong>Select a Date Range</strong>"), start = date_filter[station_id == input$sensor, min(V1)], end = date_filter[station_id == input$sensor, max(V1)])
})
uiOutput('date_selector')

HTML("<strong>Selected Sensor</strong><br>") 
leafletOutput("map")

selected_data_pm <- reactive({
  data <- long_data[!is.na(value) & station_id==input$sensor]
  data <- dcast.data.table(data[!variable %in% c('Temperature_F', 'Humidity_%')], Timestamp~variable)
  data
})

selection1 <- reactive({
  if (!is.null(input$pm_data_date_window))
  ymd_hms(strftime(gsub(".000Z","",gsub("T"," ",input$pm_data_date_window[[1]])), "%Y-%m-%d %H:%M:%S"), tz='America/Los_Angeles') - 28800
})

selection2 <- reactive({
  if (!is.null(input$pm_data_date_window))
  ymd_hms(strftime(gsub(".000Z","",gsub("T"," ",input$pm_data_date_window[[2]])), "%Y-%m-%d %H:%M:%S"), tz='America/Los_Angeles') - 28800 + 3600
})  

output$sampleTitle <- renderText({paste("Period Selected: ", paste(selection1(), selection2(), sep=" to "), " PT", sep="")}) 
```

Single Monitor View
=====================================  
Row {data-height=400}
-----------------------------------------------------------------------
### **PM Plot** <br>*Drag to select the range of interest (drag, let the graph refresh, and drag again to zoom in more precisely). <br>Double click anywhere outside of the selected area to zoom back out.* 
```{r}
output$pm_data <- renderDygraph({
  plot_data <- selected_data_pm()[Timestamp %between% c(input$date_select[1], input$date_select[2] + 1), c('Timestamp', "PM1.0_CF_ATM_ug/m3", "PM2.5_CF_ATM_ug/m3", "PM10.0_CF_ATM_ug/m3","PM2.5_CF_1_ug/m3"), with=F]
  dygraph(plot_data, group='sgpa')
})
dygraphOutput("pm_data")
```


Row
-----------------------------------------------------------------------
### **Statistics for Selected Data**<br>*This table refreshes based on the selection above.* 
```{r}
data <- reactive({
  selected_data_pm()[Timestamp >= selection1() & Timestamp <= selection2()]
})

pm_summary <- reactive({
  long <- melt(data(), id.var = 'Timestamp')
  long_summary <- long[, list(
    'Average' = round(mean(value),2),
    'SD' = round(sd(value),2),
    'Min' = round(min(value),2),
    'Median' = round(median(value),2),
    'Max' = round(max(value),2),
    'Duration (mins)' = round(difftime(max(Timestamp), min(Timestamp), unit='mins'),2),
    'Start' = min(Timestamp),
    'Stop' = max(Timestamp)
    ), by='variable']
  print(long_summary)
})

DT::renderDataTable({DT::datatable(pm_summary(), options = list(dom = 't'))%>% formatDate(c("Start", "Stop"), method = 'toLocaleString')})
```

Row 
-----------------------------------------------------------------------
### **All Data** 
```{r}
DT::renderDataTable({DT::datatable(selected_data_pm())%>% formatDate("Timestamp", method = 'toLocaleString')})
```

Multi-Monitor View
=====================================  
Row {data-height=900}
-----------------------------------------------------------------------
<<<<<<< HEAD
### **PM Map** <br>*Based on the selections made in the [Single Monitor View](#section-single-monitor-view), this map shows the average value for the selected pollutant.* 
=======

```{r}

map_data <- reactive({
  data <- long_data[!is.na(value) & Timestamp %between% c(input$date_select[1], input$date_select[2] + 1)]
  data <- data[!variable %in% c('Temperature_F', 'Humidity_%')]
  data <- data[, .(lat = mean(as.numeric(lat)), long = mean(as.numeric(long)), min = min(value), avg=mean(value), max = max(value)), by= .(station_id, variable)]
  data <- melt.data.table(data = data, id.vars = c('station_id',"lat","long","variable"), variable.name = "stat")
  data <- data[, display := paste0(variable,"_", stat)]
  data <- dcast.data.table(data = data, formula = station_id + lat + long  ~ display, value.var = "value")
  data[, size := ifelse(station_id == input$sensor, 1.5, 1)]
  data[, stroke := ifelse(station_id == input$sensor,6, 0)]
  data[, color := ifelse(station_id == input$sensor, "red", "gray50")]
  data

})

output$bigMap <- renderLeaflet({
  
  palPM1 <- colorBin(palette = c("yellow","orange","red"), domain = map_data()$`PM1.0_CF_ATM_ug/m3_avg`, bins = 3)
  palPM10 <- colorBin(palette = c("yellow","orange","red"), domain = map_data()$`PM10.0_CF_ATM_ug/m3_avg`, bins = 3)
  palPM251 <- colorBin(palette = c("yellow","orange","red"), domain = map_data()$`PM2.5_CF_1_ug/m3_avg`, bins = 3)
  palPM25 <- colorBin(palette = c("yellow","orange","red"), domain = map_data()$`PM2.5_CF_ATM_ug/m3_avg`, bins = 3)

 leaflet(data = map_data())  %>%
      addProviderTiles(providers$CartoDB.Positron) %>% # CartoDB.Positron  or  OpenStreetMap.BlackAndWhite
       addCircleMarkers(
        radius = 8,
        color = ~ palPM10(`PM10.0_CF_ATM_ug/m3_avg`),
        weight = ~ stroke,
        fillOpacity = 0.7, group = "PM10.0_CF_ATM_ug/m3", 
        label = ~ paste0("Average: ", round(`PM10.0_CF_ATM_ug/m3_avg`, 2), " ug/m3 (min: ",round(`PM10.0_CF_ATM_ug/m3_min`, 2)," - max: ", round(`PM10.0_CF_ATM_ug/m3_max`, 2),")"),
        popup = ~ paste0("Station Number: ", station_id, "  \n  The Average value for this station in the selected time period is: ", round(`PM10.0_CF_ATM_ug/m3_avg`, 2), " (min: ",round(`PM10.0_CF_ATM_ug/m3_min`, 2)," - max: ", round(`PM10.0_CF_ATM_ug/m3_max`, 2),")")
      ) %>%
    addCircleMarkers(
        radius = 8,
        color = ~ palPM25(`PM2.5_CF_ATM_ug/m3_avg`),
        weight = ~ stroke,
        fillOpacity = 0.7, group = "PM2.5_CF_ATM_ug/m3", 
        label = ~ paste0("Average: ", round(`PM2.5_CF_ATM_ug/m3_avg`, 2), " ug/m3 (min: ",round(`PM2.5_CF_ATM_ug/m3_min`, 2)," - max: ", round(`PM2.5_CF_ATM_ug/m3_max`, 2),")"),
        popup = ~ paste0("Station Number: ", station_id, "  \n  The Average value for this station in the selected time period is: ", round(`PM2.5_CF_ATM_ug/m3_avg`, 2), " (min: ",round(`PM2.5_CF_ATM_ug/m3_min`, 2)," - max: ", round(`PM2.5_CF_ATM_ug/m3_max`, 2),")")
      ) %>%
    addCircleMarkers(
        radius = 8,
        color = ~ palPM251(`PM2.5_CF_1_ug/m3_avg`),
        weight = ~ stroke,
        fillOpacity = 0.7, group = "PM2.5_CF_1_ug/m3", 
        label = ~ paste0("Average: ", round(`PM2.5_CF_1_ug/m3_avg`, 2), " ug/m3 (min: ",round(`PM2.5_CF_1_ug/m3_min`, 2)," - max: ", round(`PM2.5_CF_1_ug/m3_max`, 2),")"),
        popup = ~ paste0("Station Number: ", station_id, "  \n  The Average value for this station in the selected time period is: ", round(`PM2.5_CF_1_ug/m3_avg`, 2), " (min: ",round(`PM2.5_CF_1_ug/m3_min`, 2)," - max: ", round(`PM2.5_CF_1_ug/m3_max`, 2),")")
      ) %>%
   addCircleMarkers(
        radius = 8,
        color = ~ palPM1(`PM1.0_CF_ATM_ug/m3_avg`),
        weight = ~ stroke,
        fillOpacity = 0.7, group = "PM1.0_CF_ATM_ug/m3", 
        label = ~ paste0("Average: ", round(`PM1.0_CF_ATM_ug/m3_avg`, 2), " ug/m3 (min: ",round(`PM1.0_CF_ATM_ug/m3_min`, 2)," - max: ", round(`PM1.0_CF_ATM_ug/m3_max`, 2),")"),
        popup = ~ paste0("Station Number: ", station_id, "  \n  The Average value for this station in the selected time period is: ", round(`PM1.0_CF_ATM_ug/m3_avg`, 2), " (min: ",round(`PM1.0_CF_ATM_ug/m3_min`, 2)," - max: ", round(`PM1.0_CF_ATM_ug/m3_max`, 2),")")
      ) %>%
  addLayersControl(
    baseGroups = c("PM10.0_CF_ATM_ug/m3", "PM2.5_CF_ATM_ug/m3", "PM2.5_CF_1_ug/m3", "PM1.0_CF_ATM_ug/m3"),
    options = layersControlOptions(collapsed = FALSE)
  )
 # %>%
 #   addLegend("bottomright", pal = palPM10, values = c("low","medium","high"),
 #    title = "Average PM",
 #    labFormat = labelFormat(suffix = "ug/m3"),
 #    opacity = 1
 #  )
     

})
 
leafletOutput("bigMap")


```

